//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSA2023_TP04_A05App
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int registration_id { get; set; }
        public Nullable<int> participant_id { get; set; }
        public Nullable<int> competition_id { get; set; }
        public Nullable<int> skill_id { get; set; }
        public string status { get; set; }
    
        public virtual competition competition { get; set; }
        public virtual participant participant { get; set; }
        public virtual skill skill { get; set; }
    }
}
