//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSA2023_TP04_A05App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSA2023_TP04_A05Entities : DbContext
    {
        public WSA2023_TP04_A05Entities()
            : base("name=WSA2023_TP04_A05Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<competition> competitions { get; set; }
        public virtual DbSet<participant> participants { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<skill> skills { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
